name: headset_connection_event
description: Flutter Plugin for headset events. Detect headset is plugged and unplugged. Get current headset state.
version: 3.1.0
author: songyiYu<songyi0207@gmail.com>, yenoss<cpg0504@gmail.com>, FlutterMoum Group<fluttermoum@gmail.com>, Blake Helms (helmsb), Rafael Delos Santos (themobilecoder)
homepage: https://github.com/themobilecoder/headset_connection_event

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  

flutter:
  plugin:
    platforms:
      android:
        package: flutter.moum.headset_connection_event
        pluginClass: HeadsetConnectionEventPlugin
      ios:
        pluginClass: HeadsetConnectionEventPlugin
